name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101' # SDK Version to use.
    - name: Build NuGet package
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: dotnet pack --configuration Release
    - name: Copy nuget.config
      run: cp .github/workflows/nuget.config ./nuget.config
    - name: Set NuGet credentials
      shell: pwsh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./.github/workflow/Set-NuGetCredentials -ConfigFile ./nuget.config -Source github -Username nloum -Password $env:GITHUB_TOKEN
    - name: Publish NuGet package
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: dotnet nuget push UtilityDisposables/bin/Release/*.nupkg -s "github" --skip-duplicate
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101' # SDK Version to use.
    - name: dotnet test
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: dotnet test --logger trx
