name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101' # SDK Version to use.
    - name: Build NuGet package
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: dotnet pack --configuration Release
      - name: Publish NuGet package
      run: dotnet nuget push UtilityDisposables/bin/Release/*.nupkg --api-key $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.101' # SDK Version to use.
    - name: dotnet test
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1
      run: dotnet test --logger trx
